FROM openjdk:17-jdk-alpine

LABEL maintainer="karthik97nagaraj@gmail.com"

VOLUME /tmp

EXPOSE 8082

ARG JAR_FILE=target/Auth-Gateway-Service-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","/app.jar"]