FROM openjdk:17-jdk-alpine

VOLUME /tmp

ADD target/Auth-Gateway-Service-0.0.1-SNAPSHOT.jar Auth-Gateway-Service-0.0.1-SNAPSHOT.jar

EXPOSE 8082

ENTRYPOINT ["java","-jar","/Auth-Gateway-Service-0.0.1-SNAPSHOT.jar"]