FROM openjdk:17-jdk-alpine

VOLUME /tmp

ADD target/Payment-Service-0.0.1-SNAPSHOT.jar Payment-Service-0.0.1-SNAPSHOT.jar

EXPOSE 8088

ENTRYPOINT ["java","-jar","/Payment-Service-0.0.1-SNAPSHOT.jar"]