FROM openjdk:17-jdk-alpine

VOLUME /tmp

ADD target/Booking-Service-0.0.1-SNAPSHOT.jar Booking-Service-0.0.1-SNAPSHOT.jar

EXPOSE 8089

ENTRYPOINT ["java","-jar","/Booking-Service-0.0.1-SNAPSHOT.jar"]